/**
 * Assemble <http://assemble.io>
 *
 * Copyright (c) 2014, Jon Schlinkert, Brian Woodward, contributors.
 * Licensed under the MIT License (MIT).
 */

module.exports = function(grunt) {
  var targets = require('./test/targets')(grunt);
  // console.log(targets);

  // Project configuration.
  grunt.initConfig({

    assemble: targets,

    // assemble: {
    //   options: {
    //     data: {title: 'Site title!'},
    //     assets: 'test/assets',
    //     helpers: ['test/helpers/*.js'],
    //     layoutdir: 'test/fixtures/layouts',
    //     layout: 'default',
    //     flatten: true
    //   },

    // clean up files generated by tests
    clean: {
      tests: ['test/actual/**/*']
    },

    // lint build, test and code files
    eslint: {
      src: ['*.js', '{lib,tasks,test}/**/*.js']
    }
  });

  // Load NPM plugins to provide the necessary tasks.
  grunt.loadNpmTasks('grunt-contrib-clean');
  grunt.loadNpmTasks('gruntify-eslint');

  // Load this plugin.
  grunt.loadTasks('tasks');

  // Task aliases
  grunt.registerTask('lint', ['eslint']);
  grunt.registerTask('test', ['clean', 'assemble']);

  // Default task.
  grunt.registerTask('default', ['lint', 'test']);
};
